services:

  db:
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always




volumes:
  db-data:
